BrainBoost/Controllers/CourseProgressController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BrainBoost.Data;
using BrainBoost.Models;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;

namespace BrainBoost.Controllers
{
    public class CourseProgressController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CourseProgressController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: CourseProgress
        public async Task<IActionResult> Index()
        {
            if (User.IsInRole("Professor") || User.IsInRole("Admin"))
            {
                TempData["Kljuc"] = _context.Professor.FirstOrDefault(p => p.Username == User.Identity.Name).UserId;
            }
            else
            {
                TempData["Kljuc"] = _context.Student.FirstOrDefault(p => p.Username == User.Identity.Name).UserId;
            }
            //Ako je profesor dohvacamo kreirane kurseve za statistiku
            if (User.IsInRole("Professor"))
            {
                var courseProgresses = await _context.CourseProgress.
                    Include(c => c.Course).
                    Include(c => c.Student).
                    Where(c => c.Course.Professor.Username.Equals(User.Identity.Name)).ToListAsync();

                ///Mapiranje podataka u custom mapu koja je proslijeđena u ViewBag, da se ne prikazuju dupli kursevi
                var courseMap = new Dictionary<int, Dictionary<string, dynamic>>();
                foreach (CourseProgress item in courseProgresses)
                {
                   if(!courseMap.ContainsKey(item.CourseId))
                    {
                        courseMap.Add(item.CourseId, new Dictionary<string, dynamic>());
                        courseMap[item.CourseId].Add("numberOfStudents", 0);
                        courseMap[item.CourseId].Add("studentsCompleted", 0);
                        courseMap[item.CourseId].Add("totalHours", 0);
                        courseMap[item.CourseId].Add("courseName", item.Course.CourseName);
                        courseMap[item.CourseId].Add("studentList", new List<Dictionary<string, dynamic>>());
                    }

                    courseMap[item.CourseId]["numberOfStudents"]++;
                    courseMap[item.CourseId]["totalHours"]+=item.Hours;

                    Dictionary<string, dynamic> student = new Dictionary<string, dynamic>();
                    student.Add("id", item.StudentId);
                    student.Add("firstName", item.Student.FirstName);
                    student.Add("lastName", item.Student.LastName);
                    student.Add("userName", item.Student.Username);
                    student.Add("hours", item.Hours);
                    courseMap[item.CourseId]["studentList"].Add(new Dictionary<string, dynamic>(student));
                    if(item.Progress >= 1)
                    {
                        courseMap[item.CourseId]["studentsCompleted"]++;
                    }

                }

                ///Sortiranje prema broju upisanih studenata
                var sourtedCourseMap = from entry in courseMap orderby entry.Value["numberOfStudents"] descending select entry;
                ViewBag.courseMap = sourtedCourseMap;

                ///Ispisivanje u konzolu
                foreach (var kvp in sourtedCourseMap)
                {
                    Console.WriteLine("Key = {0}", kvp.Key);
                    foreach (var kvp2 in kvp.Value)
                    {
                        Console.WriteLine("Key2 = {0}, Value2 = {1}", kvp2.Key, kvp2.Value);

                    }

                }

                return View("ProfessorStatistics", courseProgresses);
            }
            ///Ako je student dohvacamo enrollane kurseve za statistiku
            else
            {
                var courseProgresses = await _context.CourseProgress
                               .Include(c => c.Course)
                               .Include(c => c.Student)
                               .Where(c => c.Student.Username.Equals(User.Identity.Name))
                               .ToListAsync();
                return View(courseProgresses);
            }
        }

        // GET: CourseProgress/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.CourseProgress == null)
            {
                return NotFound();
            }

            var courseProgress = await _context.CourseProgress
                .Include(c => c.Course)
                .Include(c => c.Student)
                .FirstOrDefaultAsync(m => m.CourseProgressId == id);
            if (courseProgress == null)
            {
                return NotFound();
            }

            return View(courseProgress);
        }

        // GET: CourseProgress/Create
        public IActionResult Create()
        {
            ViewData["CourseId"] = new SelectList(_context.Course, "CourseId", "CourseId");
            ViewData["StudentId"] = new SelectList(_context.Student, "UserId", "UserId");
            return View();
        }

        // POST: CourseProgress/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CourseProgressId,StudentId,CourseId,LastAccess,Progress,IsCompleted,Hours")] CourseProgress courseProgress)
        {
            if (ModelState.IsValid)
            {
                _context.Add(courseProgress);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CourseId"] = new SelectList(_context.Course, "CourseId", "CourseId", courseProgress.CourseId);
            ViewData["StudentId"] = new SelectList(_context.Student, "UserId", "UserId", courseProgress.StudentId);
            return View(courseProgress);
        }

        // GET: CourseProgress/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.CourseProgress == null)
            {
                return NotFound();
            }

            var courseProgress = await _context.CourseProgress.FindAsync(id);
            if (courseProgress == null)
            {
                return NotFound();
            }
            ViewData["CourseId"] = new SelectList(_context.Course, "CourseId", "CourseId", courseProgress.CourseId);
            ViewData["StudentId"] = new SelectList(_context.Student, "UserId", "UserId", courseProgress.StudentId);
            return View(courseProgress);
        }

        // POST: CourseProgress/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CourseProgressId,StudentId,CourseId,LastAccess,Progress,IsCompleted,Hours")] CourseProgress courseProgress)
        {
            if (id != courseProgress.CourseProgressId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(courseProgress);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseProgressExists(courseProgress.CourseProgressId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CourseId"] = new SelectList(_context.Course, "CourseId", "CourseId", courseProgress.CourseId);
            ViewData["StudentId"] = new SelectList(_context.Student, "UserId", "UserId", courseProgress.StudentId);
            return View(courseProgress);
        }

        // GET: CourseProgress/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.CourseProgress == null)
            {
                return NotFound();
            }

            var courseProgress = await _context.CourseProgress
                .Include(c => c.Course)
                .Include(c => c.Student)
                .FirstOrDefaultAsync(m => m.CourseProgressId == id);
            if (courseProgress == null)
            {
                return NotFound();
            }

            return View(courseProgress);
        }

        // POST: CourseProgress/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.CourseProgress == null)
            {
                return Problem("Entity set 'ApplicationDbContext.CourseProgress'  is null.");
            }
            var courseProgress = await _context.CourseProgress.FindAsync(id);
            if (courseProgress != null)
            {
                _context.CourseProgress.Remove(courseProgress);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseProgressExists(int id)
        {
          return _context.CourseProgress.Any(e => e.CourseProgressId == id);
        }

        ///GET: CourseProgress/MyActiveCourses
        public IActionResult MyActiveCourses()

BrainBoost/Views/CourseProgress/CourseStatistics.cshtml
@model BrainBoost.Models.Course
@{
    ViewData["Title"] = "Course statistics";
}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CourseName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                @Html.DisplayFor(modelItem => modelItem.CourseName)
            </td>
        </tr>
    </tbody>
</table>

BrainBoost/Views/CourseProgress/Create.cshtml
@model BrainBoost.Models.CourseProgress

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>CourseProgress</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StudentId" class="control-label"></label>
                <select asp-for="StudentId" class ="form-control" asp-items="ViewBag.StudentId"></select>
            </div>
            <div class="form-group">
                <label asp-for="CourseId" class="control-label"></label>
                <select asp-for="CourseId" class ="form-control" asp-items="ViewBag.CourseId"></select>
            </div>
            <div class="form-group">
                <label asp-for="LastAccess" class="control-label"></label>
                <input asp-for="LastAccess" class="form-control" />
                <span asp-validation-for="LastAccess" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Progress" class="control-label"></label>
                <input asp-for="Progress" class="form-control" />
                <span asp-validation-for="Progress" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsCompleted" /> @Html.DisplayNameFor(model => model.IsCompleted)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Hours" class="control-label"></label>
                <input asp-for="Hours" class="form-control" />
                <span asp-validation-for="Hours" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BrainBoost/Views/CourseProgress/Delete.cshtml
@model BrainBoost.Models.CourseProgress

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CourseProgress</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Student)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Student.UserId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Course)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Course.CourseId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastAccess)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastAccess)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Progress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Progress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsCompleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsCompleted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Hours)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Hours)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CourseProgressId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BrainBoost/Views/CourseProgress/Details.cshtml
@model BrainBoost.Models.CourseProgress

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>CourseProgress</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Student)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Student.UserId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Course)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Course.CourseId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastAccess)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastAccess)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Progress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Progress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsCompleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsCompleted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Hours)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Hours)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.CourseProgressId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BrainBoost/Views/CourseProgress/Edit.cshtml
@model BrainBoost.Models.CourseProgress

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>CourseProgress</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CourseProgressId" />
            <div class="form-group">
                <label asp-for="StudentId" class="control-label"></label>
                <select asp-for="StudentId" class="form-control" asp-items="ViewBag.StudentId"></select>
                <span asp-validation-for="StudentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CourseId" class="control-label"></label>
                <select asp-for="CourseId" class="form-control" asp-items="ViewBag.CourseId"></select>
                <span asp-validation-for="CourseId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastAccess" class="control-label"></label>
                <input asp-for="LastAccess" class="form-control" />
                <span asp-validation-for="LastAccess" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Progress" class="control-label"></label>
                <input asp-for="Progress" class="form-control" />
                <span asp-validation-for="Progress" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsCompleted" /> @Html.DisplayNameFor(model => model.IsCompleted)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Hours" class="control-label"></label>
                <input asp-for="Hours" class="form-control" />
                <span asp-validation-for="Hours" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BrainBoost/Views/CourseProgress/Index.cshtml
@model IEnumerable<BrainBoost.Models.CourseProgress>


@{
    ViewData["Title"] = "Statistics";
}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
@if (Model.Count() == 0)
{
    <div style="margin-top: 20px" class="alert alert-warning" role="alert">
        Nothing to show here! You are not enrolled in any course.
    </div>
}
else
{
    <h2>Your enrolled courses</h2>
    <p style="margin-bottom: 25px">Shows how much hours you have spent on each enrolled course.</p>

    <table class="table">
        <thead>
            <tr>
                <th>
                        @Html.DisplayNameFor(model => model.Course)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastAccess)
                </th>
                <th>
                    Percentage finished
                </th>
                <th>
                    Hours viewed
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <a asp-area="" asp-controller="CourseProgress" asp-action="CourseStatistics" asp-route-id="@item.Course.CourseId">
                            @Html.DisplayFor(modelItem => item.Course.CourseName)
                        </a>
                        
                    </td>
                    @if (item.LastAccess == null)
                    {
                        <td>
                            None
                        </td>
                    }
                    else
                    {
                        <td>
                            @Html.DisplayFor(modelItem => item.LastAccess)
                        </td>
                    }

                    <td>
                        @Html.DisplayFor(modelItem => item.Progress)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Hours)
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <h2>Courses by hours viewed</h2>
    <p style="margin-bottom: 50px">Shows how much hours you have spent on each enrolled course.</p>

    <div class="chart">
        <canvas id="doughnutchart"></canvas>
    </div>
}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js"></script>
<script>

    var doughnutchartCanvas = document.getElementById("doughnutchart");

     var studentname = [];
     var score = [];

    @if(Model.Count()>0)
    {
        foreach(var item in Model)
        {
            @:studentname.push('@item.Course.CourseName');
            @:score.push(@item.Hours);
        }
    }


    var doughnutChart = new Chart(doughnutchartCanvas, {
        type: 'doughnut',
        data: {
            labels: studentname,
        datasets: [{
            data: score,
            borderWidth: 0,
            backgroundColor: [
                'rgb(255, 99, 132)',
                'rgb(54, 162, 235)',
                'rgb(157, 230, 41)',
                'rgb(41, 224, 230)',
                'rgb(255, 255, 0)'
            ],
            hoverBackgroundColor: [
                'rgb(255, 99, 132)',
                'rgb(54, 162, 235)',
                'rgb(157, 230, 41)',
                'rgb(41, 224, 230)',
                'rgb(255, 255, 0)'
            ]
        }]
    },
        options: {
            responsive:true,
            legend: {
                position: "bottom",
                labels: {
                    boxWidth: 11,
                    fontColor: "#757681",
                    fontSize: 11
                }
            }
        }
    });

</script>

BrainBoost/Views/CourseProgress/MyActiveCourses.cshtml
@{
    ViewData["Title"] = "My Active Courses";
}

<div class="text-center">
    <h1 class="display-4">My Active Courses</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BrainBoost/Views/CourseProgress/MyFinishedCourses.cshtml
@{
    ViewData["Title"] = "My Finished Courses";
}

<div class="text-center">
    <h1 class="display-4">My Finished Courses</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BrainBoost/Views/CourseProgress/ProfessorStatistics.cshtml
@model IEnumerable<BrainBoost.Models.CourseProgress>

@{
    ViewData["Title"] = "Statistics";
}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

@if (Model.Count() == 0)
{
    <div style="margin-top: 20px" class="alert alert-warning" role="alert">
        Nothing to show here! You are not enrolled in any course.
    </div>
}
else
{

    <h2>Your created courses</h2>
    <p style="margin-bottom: 25px">Shows courses that you have created</p>

    <table class="table">
        <thead>
            <tr>
                <th>
                    Course
                </th>
                <th>
                    Number of students
                </th>
                <th>
                    Students completed
                </th>
                <th>
                    Total hours viewed
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in ViewBag.courseMap)
            {
                <tr>
                    <td>
                        @item.Value["courseName"]
                    </td>
                    <td>
                        @item.Value["numberOfStudents"]
                    </td>
                    <td>
                        @item.Value["studentsCompleted"]
                    </td>
                    <td>
                        @item.Value["totalHours"]
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <h2>Course by enrolled students</h2>
    <p style="margin-bottom: 50px">Shows number of enrolled students in your courses.</p>

    <div class="chart">
        <canvas id="doughnutchart"></canvas>
    </div>

    <h2>Course by completed students</h2>
    <p style="margin-bottom: 50px">Shows number of students that finished and completed your courses.</p>

    <div class="chart">
        <canvas id="doughnutchart2"></canvas>
    </div>
}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js"></script>
<script>

    var doughnutchartCanvas = document.getElementById("doughnutchart");
    var doughnutchartCanvas2 = document.getElementById("doughnutchart2");


     var courseName = [];
    var score = [];
    var score2 = [];


    @if(Model.Count()>0)
    {
        foreach(var item in ViewBag.courseMap)
        {
            @:courseName.push('@item.Value["courseName"]');
            @:score.push(@item.Value["numberOfStudents"]);
            @:score2.push(@item.Value["studentsCompleted"]);
        }
    }


    var doughnutChart = new Chart(doughnutchartCanvas, {
        type: 'doughnut',
        data: {
            labels: courseName,
        datasets: [{
            data: score,
            borderWidth: 0,
            backgroundColor: [
                'rgb(255, 99, 132)',
                'rgb(54, 162, 235)',
                'rgb(157, 230, 41)',
                'rgb(41, 224, 230)',
                'rgb(255, 255, 0)'
            ],
            hoverBackgroundColor: [
                'rgb(255, 99, 132)',
                'rgb(54, 162, 235)',
                'rgb(157, 230, 41)',
                'rgb(41, 224, 230)',
                'rgb(255, 255, 0)'
            ]
        }]
    },
        options: {
            responsive:true,
            legend: {
                position: "bottom",
                labels: {
                    boxWidth: 11,
                    fontColor: "#757681",
                    fontSize: 11
                }
            }
        }
    });

    var doughnutChart2 = new Chart(doughnutchartCanvas2, {
        type: 'doughnut',
        data: {
            labels: courseName,
            datasets: [{
                data: score2,
                borderWidth: 0,
                backgroundColor: [
                    'rgb(255, 99, 132)',
                    'rgb(54, 162, 235)',
                    'rgb(157, 230, 41)',
                    'rgb(41, 224, 230)',
                    'rgb(255, 255, 0)'
                ],
                hoverBackgroundColor: [
                    'rgb(255, 99, 132)',
                    'rgb(54, 162, 235)',
                    'rgb(157, 230, 41)',
                    'rgb(41, 224, 230)',
                    'rgb(255, 255, 0)'
                ]
            }]
        },
        options: {
            responsive: true,
            legend: {
                position: "bottom",
                labels: {
                    boxWidth: 11,
                    fontColor: "#757681",
                    fontSize: 11
                }
            }
        }
    });

</script>